### ISSUE TITLE
Some code blocks render incorrectly

### ISSUE THREAD

**Issue by olalonde** [hzlzh/Mou-Theme#3]
The following GH markdown code block (those that start with ````language`) doesn't render as code in Mou:

```javascript
console.log('some javascript code')
```

Any chance to have support for that?

**Comment by hzlzh** [comment]
Code block is not supported by Mou, you can use inline `HTML` instead or just leave it as normal when writing markdown.

**Comment by olalonde** [comment]
Ok thanks
